### ISSUE TITLE
Are multiple untappd users/sensors possible?

### ISSUE THREAD

**Issue by danielsoar** [custom-components/sensor.untapped#13]
Just wondering if anyone has had any luck creating two untappd user sensors
I wanted to display the checkin/badge data of both me and my other half on a single page.

I only get the sensors created for the first user:

### Untappd API Sensors
- platform: untappd
  name: untappd_user1
  username: !secret untappd_username1
  id: !secret untappd_id
  secret: !secret untappd_secret

- platform: untappd
  name: untappd_user2
  username: untappd_username2
  id: !secret untappd_id
  secret: !secret untappd_secret

**Comment by iantrich** [comment]
The sensor name is not dynamic

**Comment by iantrich** [comment]
@danielsoar I liked your idea so went ahead and made the sensor name dynamic 🍻 
Should be in the next release 🎉

**Comment by danielsoar** [comment]
Love your work - thank you very much! 🍻
