### ISSUE TITLE
Convert to embedded platform

### ISSUE THREAD

**Issue by iantrich** [custom-components/sensor.untapped#15]
https://github.com/home-assistant/home-assistant/pull/19948

**Comment by ludeeus** [comment]
While you are doing structural changes, maybe also have a look at the naming ;)

**Comment by iantrich** [comment]
I don't have the ability to change the repo name. @swetoast would you be okay with giving me that access so we can rename to custom-components/untappd.sensor when this change is ready?

**Comment by ludeeus** [comment]
Don't rename the repo to `untappd.sensor` that will cause major issues, it should be `sensor.untappd`
Even with embedded platforms repo names should stay with the `domain.platform` structure

**Comment by swetoast** [comment]
@iantrich go ahead you got my blessing

**Comment by iantrich** [comment]
@swetoast you need to go into settings and add me in the collaborators section. Thanks.

**Comment by ludeeus** [comment]
For that kind of change I _think_ you need to have `admin` privileges

**Comment by swetoast** [comment]
@iantrich done
