### ISSUE TITLE
difference in updater and readme

### ISSUE THREAD

**Issue by TheRedBull205** [custom-components/sensor.untapped#18]
Just found out that the updater says a different local path than the installation notes in the readme:

custom_updater.json:
*"local_location": **"/custom_components/sensor/untappd.py",***

against readme.md:
*To get started put /custom_components/untappd/sensor.py here: <config directory>**/custom_components/untappd/sensor.py***

Also in the custom_updater.json:
"remote_location": "https://raw.githubusercontent.com/custom-components/sensor.untapped/master/custom_components/sensor/untappd.py",
Should be changed to: https://raw.githubusercontent.com/custom-components/sensor.untapped/master/custom_components/untappd/sensor.py

Maybe the entire structure has to be changed but ill leave that up to you.

**Comment by iantrich** [comment]
@ludeeus that file isn't necessary anymore and can be removed, correct?

**Comment by ludeeus** [comment]
That is correct :)

https://github.com/custom-components/information/blob/master/repos.json#L250-L256

**Comment by iantrich** [comment]
@ludeeus what about root.json?

**Comment by ludeeus** [comment]
That is still there? 🤣 that is from the first "bot" I made that would generate the README when we still used gitlab :P 

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥
