### ISSUE TITLE
Platform not found: sensor.untappd

### ISSUE THREAD

**Issue by Naesstrom** [custom-components/sensor.untapped#19]
I'm getting the following error in my travis-ci builds. The same error is also stopping me from updating hass.io
```
Failed config
  General Errors: 
    - Platform not found: sensor.untappd
```
Install location:
`custom_components/untappd/sensor.py`

Configuration:
https://github.com/Naesstrom/home_assistant/blob/master/packages/untappd.yaml

**Comment by iantrich** [comment]
I missed this one, @Naesstrom did you get this sorted out?

**Comment by Naesstrom** [comment]
Actually no, still getting the same error in [Travis CI](https://travis-ci.org/Naesstrom/home_assistant/jobs/526085124#L523)
Don't have that problem with any of my other custom components so just confusing what's causing it!

**Comment by garnern2** [comment]
Did you ever get a fix for this Naesstrom?

**Comment by swetoast** [comment]
ping @ludeeus @iantrich is there an issue with this component in the lastest revision at all ?

**Comment by garnern2** [comment]
Leave this one open, close mine, even though mine is still very much an issue. Quite confusing.

It’s also not that I “upgraded,” but rather that I just installed the add-on. I’m willing to help debug, but ignoring that there is an issue is not a solution for an add-on that is purported to be  currently supported/compatible.

I also went into more detail with my open issue.

**Comment by iantrich** [comment]
I don't do travis-ci builds and don't plan to debug this as the component seemingly works for actual installations

**Comment by garnern2** [comment]
Except I have an “actual installation” and it does not work.

**Comment by iantrich** [comment]
Then why are you commenting on this issue saying you have the same problem?

**Comment by garnern2** [comment]
I opened another issue stating that it was specifically different. Until it was closed with no resolution.

Sounds like that’s fodder for an internal discussion.

**Comment by garnern2** [comment]
BTW, the symptoms I’m having are identical based on the limited information provided.

**Comment by iantrich** [comment]
You said to close it...https://github.com/custom-components/sensor.untappd/issues/19#issuecomment-515786638

**Comment by garnern2** [comment]
That’s what I posted AFTER my issue was closed with no resolution. It was posted as a statement of irony...not a request.

**Comment by ludeeus** [comment]
> ping @ludeeus @iantrich is there an issue with this component in the lastest revision at all ?

@swetoast no, some users (hassio & docker) _may_ see this "issue" when validating the configuration.

Users relying on a CI for their workflow should add a `requirements.txt` file with all requirements from custom_components they use (they can find these in the manifest files of the integrations.)
Then install those using `python3 -m pip install -r requirements.txt` _before_ running config check.

This issue is **not** with this integration but in HA itself, and this issue should IMO be closed.
AFAIK this will be fixed to the next version 0.97 (is already in dev)

**Comment by swetoast** [comment]
@garnern2 mind trying that ? if it works ill close this thread

**Comment by swetoast** [comment]
@ludeeus tnx for the info :)
