### ISSUE TITLE
Error: - Platform not found: sensor.untappd

### ISSUE THREAD

**Issue by garnern2** [custom-components/sensor.untapped#23]
I'm getting the same error message as Naesstrom. Has there been a fix?

To clarify: I'm not certain that my issue is exactly the same. I have three available sensors for Untappd. They are: sensor.untappd_last_badge_garnern2, sensor.untappd_last_check_in_garnern2, and sensor.untappd_wishlist_garnern2. There are no other Untappd sensors.

**Comment by garnern2** [comment]
Issue closed: no resolution.

**Comment by iantrich** [comment]
@garnern2 can you provide more details on this:

* HA version and installation type
* Debug logs
* yaml configuration

**Comment by garnern2** [comment]
I will get on this as soon as I get home from work this evening. Thanks for the assistance!

**Comment by garnern2** [comment]
HA Version - 0.96.5
Installation - Hass.io on Ubuntu 18.04.2 LTS
configuration.yaml - sensor: !include sensors.yaml

In sensors.yaml:

```
# Untappd
  - platform: untappd
    username: garnern2
    id: C...7
    secret: 4...A
```

I don't see anything in the error logs referencing sensor.untappd. The three sensors that do show up are sensor.untappd_last_badge_garnern2, sensor.untappd_last_check_in_garnern2, and sensor.untappd_wishlist_garnern2. When I try to find sensor.untappd, it doesn't exist.

**Comment by iantrich** [comment]
those are the sensors produced. You don't have any issues
