### ISSUE TITLE
No new applications for Untappd’s API access

### ISSUE THREAD

**Issue by toot** [custom-components/sensor.untapped#38]
> Thank you for your interest in Untappd’s API. At this time, we are no longer accepting new applications for API access as we work to improve our review and support processes. We do not have a planned date to begin accepting new applications, so please check back soon.
> 
> If you are a current user of our API, check out your app section of this page for information about your app. If you had previously submitted a request for access, but do not see your application listed on your account, please check back later to see when we will be resuming applications.

https://untappd.com/api/register

**Comment by swetoast** [comment]
So why post here? if they arent accepting they arent we as an open software developer cant influence Untappd.

**Comment by toot** [comment]
Just meant for general information.

Wanted to set up the integration and stumbled upon this.

edit: typo

**Comment by swetoast** [comment]
https://insiders.untappd.com/

**Comment by swetoast** [comment]
Pay to play it seems

**Comment by swetoast** [comment]
@iantrich Should we retire this project ?
