### ISSUE TITLE
changing to platform so we can add more features

### ISSUE THREAD

**Issue by swetoast** [custom-components/sensor.untapped#8]
but lets say friend x checks in a beer at bar y it appears on the map with x avatar and stays there for x amount of minutes 

thoughts ?

**Comment by iantrich** [comment]
Some questions:
* Why only for a few minutes? Why not just a map of last check-ins?
* Would you configure your friend list or use your untappd friend list? Some friends can live in different areas, even continents. Would you want to map all that?
* Each app is limited to 100 calls/hour. The sensor is currently at ~48calls/hour. Getting last check-in data will be an additional 12 calls/hour for each friend. So a max of 4 friends could be added before you hit the limit which then also leaves us with no room to add more features.

**Comment by swetoast** [comment]
true 👍 but its still an idea worth exploring even in a limited state like 1 check per hour

**Comment by ludeeus** [comment]
Title is misleading, this is already a platform under the sensor domain.
To achieve your goals you need to create a component (this will handle API calls)
And various plaforms:
- Sensor
- Device tracker

**Comment by swetoast** [comment]
#fakenews
